### ISSUE TITLE
TODO: fix known bugs

### ISSUE THREAD

**Issue by HadadIdan** [TechnionYP5779/team6#301]
- [ ] Trying to rent a parking spot without being logged in opens an "ugly" pop up with error, should be more elaborated. Server side didn't get the request so it's probably front-end.

- [ ] Trying to add a parking spot  without being logged in emits "Successfully added a new spot", should emit an error message instead and/or open login. Server side didn't get the request so it's probably front-end.

- [ ] Parameters search doesn't work as expected (GPS,Technion, etc, the whole area isn problematic)

- [ ] Searching by address doesn't work if the address is sent to the server with Hebrew letters (despite choosing an English address from google's drop down list).

- [ ] Wrong username or password results in endless loading, Server side emits error with correct description so it's probably front-end.

Or is assigned to fix OurSystem implementations (if needed), Idan is assigned to fix server-side implementations (if needed), Eyal is assigned to fix front-end implementations (if needed). Follow up issues will be opened.

**Comment by EyalFaygen** [comment]
i appears that we slightly changed the json format.
akuick fix to read the correct error and it works 

![image](https://user-images.githubusercontent.com/34006139/50573639-a3981800-0de0-11e9-9631-af4c182481c3.png)
