### ISSUE TITLE
Eyal Fygen karma and todo

### ISSUE THREAD

**Issue by EyalFaygen** [TechnionYP5779/team6#66]
- [x]  Use a picture, photo or distinct, familiar, personal 

- [x] Present yourself by a not too rude **nick**  

- [x]  Describe yourself in the bio page; FYI, here is my description:
 
- [x]  State that you are (not) in search for a job, i.e., mark, or unmark this box:
  
- [x]  State that you are (not) in search for a job, i.e., mark, or unmark this box:
